"""posts table

Revision ID: 101bd9d703c9
Revises: 997cbadab5d9
Create Date: 2018-07-04 13:56:13.191721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101bd9d703c9'
down_revision = '997cbadab5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timesatmp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timesatmp'), 'post', ['timesatmp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timesatmp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
